-- Drift check for lib/subjectFamilies.js (read-only, never a migration).
--
-- The GENERAL umbrella subjects widen to a hand-written list of exam-specific
-- slugs. Unknown slugs are silently dropped by the .in() in getTutorsForBrowse,
-- so a typo or a renamed subject fails quietly rather than erroring. Paste this
-- into the Supabase SQL Editor after editing the map or after seeding new
-- subjects.
--
-- Part 1 must return ZERO rows: every mapped slug exists in the catalog.
-- Part 2 is advisory: catalog subjects that look like they belong to a family
-- but are not mapped. Review each one, then either add it to the map or ignore
-- it (Computer Science, Food Science, Physical Education and the technology
-- design subjects are excluded on purpose).

-- 1. Mapped slugs that no longer exist ------------------------------------
with mapped(slug) as (
  values
    ('act-ancient-history-t'),
    ('act-biology-t'),
    ('act-chemistry-t'),
    ('act-english-as-an-additional-language-eal-d'),
    ('act-english-t'),
    ('act-essential-english-a'),
    ('act-geography-t'),
    ('act-languages-t'),
    ('act-mathematical-applications-t'),
    ('act-mathematical-methods-t'),
    ('act-modern-history-t'),
    ('act-music-t'),
    ('act-physics-t'),
    ('act-psychology-t'),
    ('act-specialist-mathematics-t'),
    ('act-visual-arts-t'),
    ('general-art'),
    ('general-english'),
    ('general-geography'),
    ('general-history'),
    ('general-languages'),
    ('general-mathematics'),
    ('general-music'),
    ('general-science'),
    ('hsc-ancient-history'),
    ('hsc-biology'),
    ('hsc-chemistry'),
    ('hsc-english-advanced'),
    ('hsc-english-extension-1'),
    ('hsc-english-extension-2'),
    ('hsc-english-standard'),
    ('hsc-english-studies'),
    ('hsc-french'),
    ('hsc-geography'),
    ('hsc-investigating-science'),
    ('hsc-italian'),
    ('hsc-japanese'),
    ('hsc-mathematics-advanced'),
    ('hsc-mathematics-extension-1'),
    ('hsc-mathematics-extension-2'),
    ('hsc-mathematics-standard-1'),
    ('hsc-mathematics-standard-2'),
    ('hsc-modern-history'),
    ('hsc-music-1'),
    ('hsc-physics'),
    ('hsc-visual-arts'),
    ('ib-biology'),
    ('ib-chemistry'),
    ('ib-english-a-language-and-literature'),
    ('ib-english-a-literature'),
    ('ib-environmental-systems-and-societies'),
    ('ib-french-ab-initio-b'),
    ('ib-geography'),
    ('ib-german-b'),
    ('ib-history'),
    ('ib-japanese-b'),
    ('ib-mandarin-chinese-ab-initio-b'),
    ('ib-mathematics-analysis-and-approaches'),
    ('ib-mathematics-applications-and-interpretation'),
    ('ib-music'),
    ('ib-physics'),
    ('ib-psychology'),
    ('ib-spanish-ab-initio-b'),
    ('ib-visual-arts'),
    ('qce-agricultural-science'),
    ('qce-ancient-history'),
    ('qce-biology'),
    ('qce-chemistry'),
    ('qce-design'),
    ('qce-english'),
    ('qce-essential-english'),
    ('qce-essential-mathematics'),
    ('qce-general-mathematics'),
    ('qce-geography'),
    ('qce-japanese'),
    ('qce-mathematical-methods'),
    ('qce-modern-history'),
    ('qce-music'),
    ('qce-physics'),
    ('qce-psychology'),
    ('qce-specialist-mathematics'),
    ('qce-visual-art'),
    ('sace-ancient-studies'),
    ('sace-biology'),
    ('sace-chemistry'),
    ('sace-creative-arts'),
    ('sace-english'),
    ('sace-english-as-an-additional-language-eal'),
    ('sace-essential-english'),
    ('sace-essential-mathematics'),
    ('sace-general-mathematics'),
    ('sace-geography'),
    ('sace-mathematical-methods'),
    ('sace-modern-history'),
    ('sace-music'),
    ('sace-physics'),
    ('sace-psychology'),
    ('sace-specialist-mathematics'),
    ('sace-visual-arts-art'),
    ('sace-visual-arts-design'),
    ('tce-agricultural-systems'),
    ('tce-ancient-history'),
    ('tce-art-production'),
    ('tce-biology'),
    ('tce-chemistry'),
    ('tce-english'),
    ('tce-english-literature'),
    ('tce-english-writing'),
    ('tce-general-mathematics'),
    ('tce-geography'),
    ('tce-mathematics-methods'),
    ('tce-mathematics-specialist'),
    ('tce-modern-history'),
    ('tce-music'),
    ('tce-physical-sciences'),
    ('tce-physics'),
    ('tce-psychology'),
    ('tce-visual-art'),
    ('vce-biology'),
    ('vce-chemistry'),
    ('vce-english'),
    ('vce-english-as-an-additional-language-eal'),
    ('vce-english-language'),
    ('vce-further-mathematics-general-mathematics'),
    ('vce-geography'),
    ('vce-history'),
    ('vce-languages-other-than-english'),
    ('vce-literature'),
    ('vce-mathematical-methods'),
    ('vce-music'),
    ('vce-physics'),
    ('vce-psychology'),
    ('vce-specialist-mathematics'),
    ('vce-studio-arts-art-making-and-exhibiting'),
    ('vce-visual-communication-design'),
    ('wace-ancient-history'),
    ('wace-biology'),
    ('wace-chemistry'),
    ('wace-design'),
    ('wace-earth-and-environmental-science'),
    ('wace-english-atar'),
    ('wace-english-general'),
    ('wace-geography'),
    ('wace-human-biology'),
    ('wace-literature'),
    ('wace-mathematics-applications'),
    ('wace-mathematics-methods'),
    ('wace-mathematics-specialist'),
    ('wace-modern-history'),
    ('wace-music'),
    ('wace-physics'),
    ('wace-psychology'),
    ('wace-visual-arts')
)
select m.slug as missing_from_catalog
from mapped m
left join subjects s on s.slug = m.slug
where s.id is null
order by 1;

-- 2. Unmapped catalog subjects that look family-shaped --------------------
with mapped(slug) as (
  values
    ('act-ancient-history-t'),
    ('act-biology-t'),
    ('act-chemistry-t'),
    ('act-english-as-an-additional-language-eal-d'),
    ('act-english-t'),
    ('act-essential-english-a'),
    ('act-geography-t'),
    ('act-languages-t'),
    ('act-mathematical-applications-t'),
    ('act-mathematical-methods-t'),
    ('act-modern-history-t'),
    ('act-music-t'),
    ('act-physics-t'),
    ('act-psychology-t'),
    ('act-specialist-mathematics-t'),
    ('act-visual-arts-t'),
    ('general-art'),
    ('general-english'),
    ('general-geography'),
    ('general-history'),
    ('general-languages'),
    ('general-mathematics'),
    ('general-music'),
    ('general-science'),
    ('hsc-ancient-history'),
    ('hsc-biology'),
    ('hsc-chemistry'),
    ('hsc-english-advanced'),
    ('hsc-english-extension-1'),
    ('hsc-english-extension-2'),
    ('hsc-english-standard'),
    ('hsc-english-studies'),
    ('hsc-french'),
    ('hsc-geography'),
    ('hsc-investigating-science'),
    ('hsc-italian'),
    ('hsc-japanese'),
    ('hsc-mathematics-advanced'),
    ('hsc-mathematics-extension-1'),
    ('hsc-mathematics-extension-2'),
    ('hsc-mathematics-standard-1'),
    ('hsc-mathematics-standard-2'),
    ('hsc-modern-history'),
    ('hsc-music-1'),
    ('hsc-physics'),
    ('hsc-visual-arts'),
    ('ib-biology'),
    ('ib-chemistry'),
    ('ib-english-a-language-and-literature'),
    ('ib-english-a-literature'),
    ('ib-environmental-systems-and-societies'),
    ('ib-french-ab-initio-b'),
    ('ib-geography'),
    ('ib-german-b'),
    ('ib-history'),
    ('ib-japanese-b'),
    ('ib-mandarin-chinese-ab-initio-b'),
    ('ib-mathematics-analysis-and-approaches'),
    ('ib-mathematics-applications-and-interpretation'),
    ('ib-music'),
    ('ib-physics'),
    ('ib-psychology'),
    ('ib-spanish-ab-initio-b'),
    ('ib-visual-arts'),
    ('qce-agricultural-science'),
    ('qce-ancient-history'),
    ('qce-biology'),
    ('qce-chemistry'),
    ('qce-design'),
    ('qce-english'),
    ('qce-essential-english'),
    ('qce-essential-mathematics'),
    ('qce-general-mathematics'),
    ('qce-geography'),
    ('qce-japanese'),
    ('qce-mathematical-methods'),
    ('qce-modern-history'),
    ('qce-music'),
    ('qce-physics'),
    ('qce-psychology'),
    ('qce-specialist-mathematics'),
    ('qce-visual-art'),
    ('sace-ancient-studies'),
    ('sace-biology'),
    ('sace-chemistry'),
    ('sace-creative-arts'),
    ('sace-english'),
    ('sace-english-as-an-additional-language-eal'),
    ('sace-essential-english'),
    ('sace-essential-mathematics'),
    ('sace-general-mathematics'),
    ('sace-geography'),
    ('sace-mathematical-methods'),
    ('sace-modern-history'),
    ('sace-music'),
    ('sace-physics'),
    ('sace-psychology'),
    ('sace-specialist-mathematics'),
    ('sace-visual-arts-art'),
    ('sace-visual-arts-design'),
    ('tce-agricultural-systems'),
    ('tce-ancient-history'),
    ('tce-art-production'),
    ('tce-biology'),
    ('tce-chemistry'),
    ('tce-english'),
    ('tce-english-literature'),
    ('tce-english-writing'),
    ('tce-general-mathematics'),
    ('tce-geography'),
    ('tce-mathematics-methods'),
    ('tce-mathematics-specialist'),
    ('tce-modern-history'),
    ('tce-music'),
    ('tce-physical-sciences'),
    ('tce-physics'),
    ('tce-psychology'),
    ('tce-visual-art'),
    ('vce-biology'),
    ('vce-chemistry'),
    ('vce-english'),
    ('vce-english-as-an-additional-language-eal'),
    ('vce-english-language'),
    ('vce-further-mathematics-general-mathematics'),
    ('vce-geography'),
    ('vce-history'),
    ('vce-languages-other-than-english'),
    ('vce-literature'),
    ('vce-mathematical-methods'),
    ('vce-music'),
    ('vce-physics'),
    ('vce-psychology'),
    ('vce-specialist-mathematics'),
    ('vce-studio-arts-art-making-and-exhibiting'),
    ('vce-visual-communication-design'),
    ('wace-ancient-history'),
    ('wace-biology'),
    ('wace-chemistry'),
    ('wace-design'),
    ('wace-earth-and-environmental-science'),
    ('wace-english-atar'),
    ('wace-english-general'),
    ('wace-geography'),
    ('wace-human-biology'),
    ('wace-literature'),
    ('wace-mathematics-applications'),
    ('wace-mathematics-methods'),
    ('wace-mathematics-specialist'),
    ('wace-modern-history'),
    ('wace-music'),
    ('wace-physics'),
    ('wace-psychology'),
    ('wace-visual-arts')
)
select s.exam_code, s.slug, s.name
from subjects s
where s.exam_code not in ('GENERAL', 'TEST')
  and s.slug not in (select slug from mapped)
  and (
    s.name ~* 'english|literature|\meal\M'
    or s.name ~* 'math'
    or s.name ~* 'biolog|chemis|physic|psycholog|\mscience\M|environmental'
    or s.name ~* 'history'
    or s.name ~* 'geograph'
    or s.name ~* 'art\M|visual|studio'
    or s.name ~* 'music'
    or s.name ~* 'language|japanese|french|italian|german|spanish|mandarin|chinese'
  )
order by s.exam_code, s.name;
