export const TUTORS = [
  {
    id: "amelia-chen",
    name: "Amelia Chen",
    role: "Private Tutor · Mathematics & Physics",
    city: "Sydney, NSW",
    suburb: "Chatswood",
    avatarBg: "oklch(0.85 0.04 250)",
    initial: "AC",
    atar: 99.85,
    rank: "State Rank in Mathematics Extension 2",
    rate: 85,
    online: true,
    verified: true,
    responsive: "Very responsive",
    rating: 4.9,
    reviews: 47,
    subjects: ["Mathematics Ext 2", "Mathematics Ext 1", "Physics", "Chemistry", "Mathematics Advanced"],
    bio: "Currently studying B. Engineering (Honours) / B. Commerce at UNSW. I help senior students build a deep, intuitive feel for Maths and Physics — the kind that makes hard exam questions feel obvious rather than memorised.",
    bioLong: "I tutor HSC Mathematics Extension 1 & 2, Physics, and Chemistry. My students range from those aiming for a Band 6 to those pushing for a state rank. The work we do together is rigorous: we go past surface-level mark schemes, into the structures examiners are testing for. I prep custom problem sets weekly based on what we cover in class and what's coming up in your school's assessment schedule.\n\nI've helped 40+ students through their HSC over the last three years. Most see a 10–20 mark improvement on trial-to-HSC. I work in person in the Lower North Shore or online via shared whiteboard.",
    location: "Lower North Shore + Online",
    yearsTutoring: 3,
    school: "James Ruse Agricultural High School",
    schoolYear: "Class of 2023",
    university: "University of New South Wales",
    degree: "B. Engineering (Honours) / B. Commerce",
    degreeYear: "Expected 2027",
    credentials: ["99.85 ATAR", "State Rank Maths Ext 2", "All-Rounder 2023", "Premier's Award"],
    languages: ["English", "Mandarin"],
    verifications: [
      { label: "Verified identity", done: true },
      { label: "Verified mobile", done: true },
      { label: "Verified ATAR & marks", done: true },
      { label: "Working with Children check", done: true },
      { label: "References (3)", done: true },
    ],
    packages: [
      { label: "Single lesson", duration: "60 min", price: 85 },
      { label: "5-lesson pack", duration: "5 × 60 min", price: 400, save: "save $25" },
      { label: "10-lesson pack", duration: "10 × 60 min", price: 750, save: "save $100" },
    ],
    experience: [
      { role: "Private Tutor (self-employed)", org: "Mathematics & Physics", period: "2024 — present", note: "40+ HSC students. Specialising in Ext 2 and high-band Physics." },
      { role: "Academic Mentor", org: "James Ruse Mentor Program", period: "2023 — 2024", note: "Mentored Year 11 students through Ext 1 transition." },
      { role: "Maths Olympiad Coach", org: "AMT — Junior Squad", period: "2022 — 2023", note: "Coached selected Year 10s on competition problem-solving." },
    ],
    education: [
      { school: "University of New South Wales", detail: "B. Engineering (Hons) / B. Commerce — expected 2027" },
      { school: "James Ruse Agricultural High School", detail: "ATAR 99.85, Class of 2023" },
    ],
    reviewsList: [
      { name: "Priya M.", role: "Parent · Year 12", date: "Mar 2026", body: "Amelia took my son from a Band 4 in Ext 1 to high Band 5 in two terms. She is patient, prepared, and never wastes a session. Worth every dollar." },
      { name: "Daniel W.", role: "Student · Year 12", date: "Feb 2026", body: "Genuinely the first tutor who explained Mechanics in a way that stuck. We work through past papers and she shows me the thinking, not just the answer." },
      { name: "Linh T.", role: "Parent · Year 11", date: "Nov 2025", body: "We were nervous because my daughter's previous tutor was much older. Amelia is calm, professional, and gets results. Highly recommend." },
      { name: "Marcus O.", role: "Student · Year 12", date: "Oct 2025", body: "Went from 78 to 91 in Maths Ext 1 between trials and HSC. The custom problem sets are the key — they're harder than what school gives you." },
    ],
    availability: {
      hours: ["4pm", "5pm", "6pm", "7pm", "8pm"],
      days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      grid: [
        [0, 1, 1, 0, 1, 1, 0],
        [1, 2, 1, 1, 2, 1, 0],
        [1, 1, 2, 1, 1, 1, 1],
        [2, 1, 1, 2, 1, 0, 0],
        [1, 0, 1, 1, 0, 0, 0],
      ],
    },
  },
  {
    id: "rohan-patel",
    name: "Rohan Patel",
    role: "Private Tutor · English & Literature",
    city: "Sydney, NSW",
    suburb: "Glebe",
    avatarBg: "oklch(0.86 0.04 80)",
    initial: "RP",
    atar: 99.50,
    rank: "Premier's Award · English",
    rate: 75,
    online: true,
    verified: true,
    responsive: "Very responsive",
    rating: 4.9,
    reviews: 38,
    subjects: ["English Advanced", "English Extension 1", "English Extension 2"],
    bio: "Premier's Award recipient. I coach senior English and Literature students from a Band 4 into a Band 6 — through close reading, argument scaffolding, and weekly essay feedback.",
    credentials: ["99.50 ATAR", "Premier's Award English", "Band 6 English Adv"],
  },
  {
    id: "saskia-nguyen",
    name: "Saskia Nguyen",
    role: "Private Tutor · Biology & Chemistry",
    city: "Sydney, NSW",
    suburb: "Strathfield",
    avatarBg: "oklch(0.86 0.04 160)",
    initial: "SN",
    atar: 99.20,
    rank: "Dux of school 2024",
    rate: 70,
    online: true,
    verified: true,
    responsive: "Usually responds within 1 hour",
    rating: 5.0,
    reviews: 22,
    subjects: ["Biology", "Chemistry", "Mathematics Standard"],
    bio: "Medical student. Specialising in Biology and Chemistry — I teach the syllabus the way examiners read it, not the way textbooks write it.",
    credentials: ["99.20 ATAR", "Dux 2024", "Medical Faculty"],
  },
  {
    id: "tom-baxter",
    name: "Tom Baxter",
    role: "Private Tutor · Mathematics & Physics",
    city: "Sydney, NSW",
    suburb: "Mosman",
    avatarBg: "oklch(0.86 0.04 30)",
    initial: "TB",
    atar: 99.95,
    rank: "All-Rounder 2023",
    rate: 110,
    online: false,
    verified: true,
    responsive: "Responsive",
    rating: 4.8,
    reviews: 31,
    subjects: ["Mathematics Ext 2", "Mathematics Ext 1", "Physics"],
    bio: "ATAR 99.95. Now studying Mathematics at the University of Sydney. I work with motivated senior students pushing for Band 6 in Maths Ext 2 and Physics.",
    credentials: ["99.95 ATAR", "AMO Bronze", "USyd Maths"],
  },
  {
    id: "leila-osman",
    name: "Leila Osman",
    role: "Private Tutor · English & Modern History",
    city: "Sydney, NSW",
    suburb: "Newtown",
    avatarBg: "oklch(0.86 0.04 320)",
    initial: "LO",
    atar: 99.05,
    rank: "Band 6 English Adv & Ext 1",
    rate: 70,
    online: true,
    verified: true,
    responsive: "Very responsive",
    rating: 4.9,
    reviews: 56,
    subjects: ["English Advanced", "English Extension 1", "Modern History", "Society & Culture"],
    bio: "I teach essay writing as a craft. My students learn to read texts critically and write thesis-led, structurally tight essays that hold up under HSC marking.",
    credentials: ["99.05 ATAR", "Band 6 English Adv", "USyd Arts/Law"],
  },
  {
    id: "noah-fisher",
    name: "Noah Fisher",
    role: "Private Tutor · UCAT & Medical Entry",
    city: "Sydney, NSW",
    suburb: "Camperdown",
    avatarBg: "oklch(0.86 0.04 220)",
    initial: "NF",
    atar: 99.80,
    rank: "UCAT 3380 (99th percentile)",
    rate: 95,
    online: true,
    verified: true,
    responsive: "Responsive",
    rating: 5.0,
    reviews: 19,
    subjects: ["UCAT", "Interview prep", "Biology"],
    bio: "Second-year medical student at UNSW. UCAT 3380. I tutor students preparing for UCAT and medical school interviews — structured drills, timing strategy, and mock interviews on Zoom.",
    credentials: ["UCAT 3380", "UNSW Medicine", "Interview panel coach"],
  },
  {
    id: "yusra-khan",
    name: "Yusra Khan",
    role: "Private Tutor · LSAT & Legal Reasoning",
    city: "Sydney, NSW",
    suburb: "Surry Hills",
    avatarBg: "oklch(0.86 0.04 110)",
    initial: "YK",
    atar: 99.40,
    rank: "LSAT 175 / 180",
    rate: 90,
    online: true,
    verified: true,
    responsive: "Very responsive",
    rating: 4.9,
    reviews: 27,
    subjects: ["LSAT", "Logical Reasoning", "Reading Comprehension"],
    bio: "LSAT 175. I help students preparing for US and Australian law school admissions — full-length timed sections, weekly feedback, and a custom drilling plan for Logic Games and Reading Comp.",
    credentials: ["LSAT 175", "USyd Law", "Law Admissions Coach"],
  },
  {
    id: "harvey-lim",
    name: "Harvey Lim",
    role: "Private Tutor · Economics & Business",
    city: "Sydney, NSW",
    suburb: "Burwood",
    avatarBg: "oklch(0.86 0.04 200)",
    initial: "HL",
    atar: 98.95,
    rank: "Band 6 Economics",
    rate: 65,
    online: false,
    verified: true,
    responsive: "Responsive",
    rating: 4.7,
    reviews: 41,
    subjects: ["Economics", "Business Studies", "Legal Studies"],
    bio: "Commerce/Law at UNSW. I tutor HSC Economics and Business — focus on diagram-driven essay writing and current event integration.",
    credentials: ["98.95 ATAR", "Band 6 Economics", "UNSW Comm/Law"],
  },
  {
    id: "isabelle-park",
    name: "Isabelle Park",
    role: "Private Tutor · Chemistry & Biology",
    city: "Sydney, NSW",
    suburb: "Hornsby",
    avatarBg: "oklch(0.86 0.04 280)",
    initial: "IP",
    atar: 99.60,
    rank: "All-Rounder 2024",
    rate: 80,
    online: true,
    verified: true,
    responsive: "Very responsive",
    rating: 4.9,
    reviews: 33,
    subjects: ["Chemistry", "Biology", "Mathematics Standard"],
    bio: "Medical student at USyd. I tutor HSC Chemistry and Biology — module-by-module, with custom flashcards and weekly recall checks.",
    credentials: ["99.60 ATAR", "All-Rounder 2024", "USyd Medicine"],
  },
];

export const SUBJECTS = [
  "Mathematics Advanced",
  "Mathematics Ext 1",
  "Mathematics Ext 2",
  "Mathematics Standard",
  "Physics",
  "Chemistry",
  "Biology",
  "English Advanced",
  "English Extension 1",
  "English Extension 2",
  "Modern History",
  "Society & Culture",
  "Economics",
  "Business Studies",
  "Legal Studies",
  "UCAT",
  "LSAT",
];

export const CONVERSATIONS = [
  {
    id: "c1",
    tutorId: "amelia-chen",
    lastSnippet: "Sounds good — Wednesday 5pm works. I'll send you a problem set tonight.",
    lastTime: "11:42 AM",
    unread: 0,
    online: true,
    messages: [
      { from: "tutor", time: "Mon 4:12pm", text: "Hi! Thanks for reaching out. I'd love to help your son with Ext 2." },
      { from: "tutor", time: "Mon 4:12pm", text: "Can you tell me a bit about where he's at — recent assessment marks, modules covered so far, and what he's finding hardest?" },
      { from: "me", time: "Mon 5:30pm", text: "Hi Amelia — thanks for the quick reply. He's on 78% in Ext 2, struggling most with Mechanics and Complex Numbers. Trials are in 6 weeks." },
      { from: "me", time: "Mon 5:31pm", text: "Are you available Wednesdays around 5pm? In-person preferred if you can come to Chatswood." },
      { from: "tutor", time: "Mon 8:04pm", text: "Wednesdays at 5pm work well for me. I'm in Chatswood already, happy to do in-person." },
      { from: "tutor", time: "Mon 8:05pm", text: "Mechanics + Complex Numbers is a common pairing — they're both rep-heavy. Six weeks is enough if we run weekly with a problem set in between." },
      { from: "me", time: "Tue 9:10am", text: "Perfect. Let's lock it in. Rate is $85/hr — happy to do the 5-pack." },
      { from: "tutor", time: "Today 11:42am", text: "Sounds good — Wednesday 5pm works. I'll send you a problem set tonight." },
    ],
  },
  {
    id: "c2",
    tutorId: "rohan-patel",
    lastSnippet: "Happy to do a free 20-min intro call this week if it helps.",
    lastTime: "Yesterday",
    unread: 2,
    online: false,
    messages: [
      { from: "tutor", time: "Yesterday", text: "Hi — thanks for the message. Year 11 Lit is a great time to start." },
      { from: "tutor", time: "Yesterday", text: "Happy to do a free 20-min intro call this week if it helps." },
    ],
  },
  {
    id: "c3",
    tutorId: "leila-osman",
    lastSnippet: "I've attached a sample essay framework — let me know what you think.",
    lastTime: "Sun",
    unread: 0,
    online: true,
    messages: [
      { from: "me", time: "Sun 2:00pm", text: "Hi Leila, looking for help with Mod B essays." },
      { from: "tutor", time: "Sun 4:15pm", text: "I've attached a sample essay framework — let me know what you think." },
    ],
  },
  {
    id: "c4",
    tutorId: "noah-fisher",
    lastSnippet: "Mock interview slot Saturday morning still open.",
    lastTime: "Fri",
    unread: 0,
    online: false,
    messages: [
      { from: "tutor", time: "Fri", text: "Mock interview slot Saturday morning still open." },
    ],
  },
];

export const getTutor = (id) => TUTORS.find((t) => t.id === id);
