-- 0009_subject_catalog.sql
-- Replaces the 17 seeded subjects (HSC + UCAT/LSAT) from 0002 with an extensive,
-- certificate-scoped Australian subject catalog. The same display name (Biology,
-- English, Physics, ...) recurs across certificates, so subjects are now scoped
-- to a certificate and the old `subjects.name` UNIQUE constraint is dropped;
-- `slug` (certificate-prefixed, e.g. 'vce-biology') stays the unique canonical key.
--
-- WIPE & RESEED: existing subjects + their tutor_subjects links are cleared. Tutors
-- re-pick subjects from the new catalog. (Pre-launch; acceptable data loss.)
--
-- 254 subjects across 9 certificate groups.

-- 1. certificates reference table --------------------------------------------

create table public.certificates (
  code           text primary key,            -- 'HSC','VCE',...,'TEST'
  name           text not null,
  jurisdiction   text,                         -- null for TEST
  external_exams boolean,                       -- null for TEST
  position       int  not null default 0
);

insert into public.certificates (code, name, jurisdiction, external_exams, position) values
  ('HSC', 'Higher School Certificate', 'New South Wales', true, 1),
  ('VCE', 'Victorian Certificate of Education', 'Victoria', true, 2),
  ('IB', 'International Baccalaureate Diploma Programme', 'International (offered Australia-wide)', true, 3),
  ('QCE', 'Queensland Certificate of Education', 'Queensland', true, 4),
  ('SACE', 'South Australian Certificate of Education', 'South Australia & Northern Territory', true, 5),
  ('WACE', 'Western Australian Certificate of Education', 'Western Australia', true, 6),
  ('TCE', 'Tasmanian Certificate of Education', 'Tasmania', true, 7),
  ('ACT', 'ACT Senior Secondary Certificate', 'Australian Capital Territory', false, 8),
  ('TEST', 'Admissions & Aptitude Tests', null, null, 9);

alter table public.certificates enable row level security;
create policy "certificates public read"
  on public.certificates for select using (true);

-- 2. reseed subjects (certificate-scoped) ------------------------------------

delete from public.tutor_subjects;            -- FK cascade would also clear these
delete from public.subjects;

alter table public.subjects drop constraint subjects_name_key;   -- name no longer globally unique
alter table public.subjects add column certificate_code text references public.certificates(code);

insert into public.subjects (name, slug, certificate_code, position) values
  ('English Standard', 'hsc-english-standard', 'HSC', 1),
  ('Mathematics Standard 2', 'hsc-mathematics-standard-2', 'HSC', 2),
  ('English Advanced', 'hsc-english-advanced', 'HSC', 3),
  ('Biology', 'hsc-biology', 'HSC', 4),
  ('Business Studies', 'hsc-business-studies', 'HSC', 5),
  ('Personal Development, Health and Physical Education (PDHPE)', 'hsc-personal-development-health-and-physical-education-pdhpe', 'HSC', 6),
  ('Mathematics Advanced', 'hsc-mathematics-advanced', 'HSC', 7),
  ('English Studies', 'hsc-english-studies', 'HSC', 8),
  ('Modern History', 'hsc-modern-history', 'HSC', 9),
  ('Chemistry', 'hsc-chemistry', 'HSC', 10),
  ('Legal Studies', 'hsc-legal-studies', 'HSC', 11),
  ('Community and Family Studies', 'hsc-community-and-family-studies', 'HSC', 12),
  ('Mathematics Extension 1', 'hsc-mathematics-extension-1', 'HSC', 13),
  ('Visual Arts', 'hsc-visual-arts', 'HSC', 14),
  ('Physics', 'hsc-physics', 'HSC', 15),
  ('Studies of Religion I', 'hsc-studies-of-religion-i', 'HSC', 16),
  ('Mathematics Standard 1', 'hsc-mathematics-standard-1', 'HSC', 17),
  ('Ancient History', 'hsc-ancient-history', 'HSC', 18),
  ('Studies of Religion II', 'hsc-studies-of-religion-ii', 'HSC', 19),
  ('Industrial Technology', 'hsc-industrial-technology', 'HSC', 20),
  ('Economics', 'hsc-economics', 'HSC', 21),
  ('Society and Culture', 'hsc-society-and-culture', 'HSC', 22),
  ('Music 1', 'hsc-music-1', 'HSC', 23),
  ('Geography', 'hsc-geography', 'HSC', 24),
  ('Food Technology', 'hsc-food-technology', 'HSC', 25),
  ('Design and Technology', 'hsc-design-and-technology', 'HSC', 26),
  ('Mathematics Extension 2', 'hsc-mathematics-extension-2', 'HSC', 27),
  ('English Extension 1', 'hsc-english-extension-1', 'HSC', 28),
  ('Investigating Science', 'hsc-investigating-science', 'HSC', 29),
  ('Drama', 'hsc-drama', 'HSC', 30),
  ('English', 'vce-english', 'VCE', 1),
  ('English as an Additional Language (EAL)', 'vce-english-as-an-additional-language-eal', 'VCE', 2),
  ('Mathematical Methods', 'vce-mathematical-methods', 'VCE', 3),
  ('Further Mathematics / General Mathematics', 'vce-further-mathematics-general-mathematics', 'VCE', 4),
  ('Biology', 'vce-biology', 'VCE', 5),
  ('Chemistry', 'vce-chemistry', 'VCE', 6),
  ('Psychology', 'vce-psychology', 'VCE', 7),
  ('Physical Education', 'vce-physical-education', 'VCE', 8),
  ('Business Management', 'vce-business-management', 'VCE', 9),
  ('Health and Human Development', 'vce-health-and-human-development', 'VCE', 10),
  ('Specialist Mathematics', 'vce-specialist-mathematics', 'VCE', 11),
  ('Physics', 'vce-physics', 'VCE', 12),
  ('Legal Studies', 'vce-legal-studies', 'VCE', 13),
  ('Economics', 'vce-economics', 'VCE', 14),
  ('Accounting', 'vce-accounting', 'VCE', 15),
  ('History', 'vce-history', 'VCE', 16),
  ('Studio Arts / Art Making and Exhibiting', 'vce-studio-arts-art-making-and-exhibiting', 'VCE', 17),
  ('Geography', 'vce-geography', 'VCE', 18),
  ('Literature', 'vce-literature', 'VCE', 19),
  ('English Language', 'vce-english-language', 'VCE', 20),
  ('Visual Communication Design', 'vce-visual-communication-design', 'VCE', 21),
  ('Media', 'vce-media', 'VCE', 22),
  ('Product Design and Technology', 'vce-product-design-and-technology', 'VCE', 23),
  ('Food Studies', 'vce-food-studies', 'VCE', 24),
  ('Information Technology / Applied Computing', 'vce-information-technology-applied-computing', 'VCE', 25),
  ('Sociology', 'vce-sociology', 'VCE', 26),
  ('Politics', 'vce-politics', 'VCE', 27),
  ('Drama', 'vce-drama', 'VCE', 28),
  ('Music', 'vce-music', 'VCE', 29),
  ('Languages Other Than English', 'vce-languages-other-than-english', 'VCE', 30),
  ('Theory of Knowledge (TOK)', 'ib-theory-of-knowledge-tok', 'IB', 1),
  ('Extended Essay (EE)', 'ib-extended-essay-ee', 'IB', 2),
  ('Creativity, Activity, Service (CAS)', 'ib-creativity-activity-service-cas', 'IB', 3),
  ('English A: Language and Literature', 'ib-english-a-language-and-literature', 'IB', 4),
  ('English A: Literature', 'ib-english-a-literature', 'IB', 5),
  ('French ab initio / B', 'ib-french-ab-initio-b', 'IB', 6),
  ('Spanish ab initio / B', 'ib-spanish-ab-initio-b', 'IB', 7),
  ('Mandarin (Chinese) ab initio / B', 'ib-mandarin-chinese-ab-initio-b', 'IB', 8),
  ('Japanese B', 'ib-japanese-b', 'IB', 9),
  ('German B', 'ib-german-b', 'IB', 10),
  ('Economics', 'ib-economics', 'IB', 11),
  ('Business Management', 'ib-business-management', 'IB', 12),
  ('History', 'ib-history', 'IB', 13),
  ('Geography', 'ib-geography', 'IB', 14),
  ('Psychology', 'ib-psychology', 'IB', 15),
  ('Global Politics', 'ib-global-politics', 'IB', 16),
  ('Philosophy', 'ib-philosophy', 'IB', 17),
  ('Environmental Systems and Societies', 'ib-environmental-systems-and-societies', 'IB', 18),
  ('Biology', 'ib-biology', 'IB', 19),
  ('Chemistry', 'ib-chemistry', 'IB', 20),
  ('Physics', 'ib-physics', 'IB', 21),
  ('Computer Science', 'ib-computer-science', 'IB', 22),
  ('Sports, Exercise and Health Science', 'ib-sports-exercise-and-health-science', 'IB', 23),
  ('Design Technology', 'ib-design-technology', 'IB', 24),
  ('Mathematics: Analysis and Approaches', 'ib-mathematics-analysis-and-approaches', 'IB', 25),
  ('Mathematics: Applications and Interpretation', 'ib-mathematics-applications-and-interpretation', 'IB', 26),
  ('Visual Arts', 'ib-visual-arts', 'IB', 27),
  ('Music', 'ib-music', 'IB', 28),
  ('Theatre', 'ib-theatre', 'IB', 29),
  ('Film', 'ib-film', 'IB', 30),
  ('English', 'qce-english', 'QCE', 1),
  ('General Mathematics', 'qce-general-mathematics', 'QCE', 2),
  ('Mathematical Methods', 'qce-mathematical-methods', 'QCE', 3),
  ('Essential English', 'qce-essential-english', 'QCE', 4),
  ('Biology', 'qce-biology', 'QCE', 5),
  ('Chemistry', 'qce-chemistry', 'QCE', 6),
  ('Physics', 'qce-physics', 'QCE', 7),
  ('Modern History', 'qce-modern-history', 'QCE', 8),
  ('Ancient History', 'qce-ancient-history', 'QCE', 9),
  ('Geography', 'qce-geography', 'QCE', 10),
  ('Legal Studies', 'qce-legal-studies', 'QCE', 11),
  ('Business', 'qce-business', 'QCE', 12),
  ('Economics', 'qce-economics', 'QCE', 13),
  ('Accounting', 'qce-accounting', 'QCE', 14),
  ('Psychology', 'qce-psychology', 'QCE', 15),
  ('Physical Education', 'qce-physical-education', 'QCE', 16),
  ('Health', 'qce-health', 'QCE', 17),
  ('Specialist Mathematics', 'qce-specialist-mathematics', 'QCE', 18),
  ('Essential Mathematics', 'qce-essential-mathematics', 'QCE', 19),
  ('Visual Art', 'qce-visual-art', 'QCE', 20),
  ('Drama', 'qce-drama', 'QCE', 21),
  ('Music', 'qce-music', 'QCE', 22),
  ('Film, Television and New Media', 'qce-film-television-and-new-media', 'QCE', 23),
  ('Design', 'qce-design', 'QCE', 24),
  ('Digital Solutions', 'qce-digital-solutions', 'QCE', 25),
  ('Information and Communication Technology', 'qce-information-and-communication-technology', 'QCE', 26),
  ('Food and Nutrition', 'qce-food-and-nutrition', 'QCE', 27),
  ('Agricultural Science', 'qce-agricultural-science', 'QCE', 28),
  ('Study of Religion', 'qce-study-of-religion', 'QCE', 29),
  ('Japanese', 'qce-japanese', 'QCE', 30),
  ('Research Project', 'sace-research-project', 'SACE', 1),
  ('English', 'sace-english', 'SACE', 2),
  ('English as an Additional Language (EAL)', 'sace-english-as-an-additional-language-eal', 'SACE', 3),
  ('Essential English', 'sace-essential-english', 'SACE', 4),
  ('Mathematical Methods', 'sace-mathematical-methods', 'SACE', 5),
  ('General Mathematics', 'sace-general-mathematics', 'SACE', 6),
  ('Specialist Mathematics', 'sace-specialist-mathematics', 'SACE', 7),
  ('Essential Mathematics', 'sace-essential-mathematics', 'SACE', 8),
  ('Biology', 'sace-biology', 'SACE', 9),
  ('Chemistry', 'sace-chemistry', 'SACE', 10),
  ('Physics', 'sace-physics', 'SACE', 11),
  ('Psychology', 'sace-psychology', 'SACE', 12),
  ('Modern History', 'sace-modern-history', 'SACE', 13),
  ('Ancient Studies', 'sace-ancient-studies', 'SACE', 14),
  ('Geography', 'sace-geography', 'SACE', 15),
  ('Legal Studies', 'sace-legal-studies', 'SACE', 16),
  ('Business Innovation', 'sace-business-innovation', 'SACE', 17),
  ('Accounting', 'sace-accounting', 'SACE', 18),
  ('Economics', 'sace-economics', 'SACE', 19),
  ('Physical Education', 'sace-physical-education', 'SACE', 20),
  ('Health and Wellbeing', 'sace-health-and-wellbeing', 'SACE', 21),
  ('Nutrition', 'sace-nutrition', 'SACE', 22),
  ('Visual Arts - Art', 'sace-visual-arts-art', 'SACE', 23),
  ('Visual Arts - Design', 'sace-visual-arts-design', 'SACE', 24),
  ('Drama', 'sace-drama', 'SACE', 25),
  ('Music', 'sace-music', 'SACE', 26),
  ('Creative Arts', 'sace-creative-arts', 'SACE', 27),
  ('Food and Hospitality', 'sace-food-and-hospitality', 'SACE', 28),
  ('Digital Technologies', 'sace-digital-technologies', 'SACE', 29),
  ('Society and Culture', 'sace-society-and-culture', 'SACE', 30),
  ('English (ATAR)', 'wace-english-atar', 'WACE', 1),
  ('English (General)', 'wace-english-general', 'WACE', 2),
  ('Mathematics Applications', 'wace-mathematics-applications', 'WACE', 3),
  ('Mathematics Methods', 'wace-mathematics-methods', 'WACE', 4),
  ('Mathematics Specialist', 'wace-mathematics-specialist', 'WACE', 5),
  ('Human Biology', 'wace-human-biology', 'WACE', 6),
  ('Biology', 'wace-biology', 'WACE', 7),
  ('Chemistry', 'wace-chemistry', 'WACE', 8),
  ('Physics', 'wace-physics', 'WACE', 9),
  ('Psychology', 'wace-psychology', 'WACE', 10),
  ('Modern History', 'wace-modern-history', 'WACE', 11),
  ('Ancient History', 'wace-ancient-history', 'WACE', 12),
  ('Geography', 'wace-geography', 'WACE', 13),
  ('Politics and Law', 'wace-politics-and-law', 'WACE', 14),
  ('Economics', 'wace-economics', 'WACE', 15),
  ('Accounting and Finance', 'wace-accounting-and-finance', 'WACE', 16),
  ('Business Management and Enterprise', 'wace-business-management-and-enterprise', 'WACE', 17),
  ('Physical Education Studies', 'wace-physical-education-studies', 'WACE', 18),
  ('Health Studies', 'wace-health-studies', 'WACE', 19),
  ('Children, Family and the Community', 'wace-children-family-and-the-community', 'WACE', 20),
  ('Literature', 'wace-literature', 'WACE', 21),
  ('Visual Arts', 'wace-visual-arts', 'WACE', 22),
  ('Drama', 'wace-drama', 'WACE', 23),
  ('Music', 'wace-music', 'WACE', 24),
  ('Media Production and Analysis', 'wace-media-production-and-analysis', 'WACE', 25),
  ('Design', 'wace-design', 'WACE', 26),
  ('Food Science and Technology', 'wace-food-science-and-technology', 'WACE', 27),
  ('Applied Information Technology / Computer Science', 'wace-applied-information-technology-computer-science', 'WACE', 28),
  ('Materials Design and Technology', 'wace-materials-design-and-technology', 'WACE', 29),
  ('Earth and Environmental Science', 'wace-earth-and-environmental-science', 'WACE', 30),
  ('English', 'tce-english', 'TCE', 1),
  ('English Writing', 'tce-english-writing', 'TCE', 2),
  ('English Literature', 'tce-english-literature', 'TCE', 3),
  ('Mathematics Methods', 'tce-mathematics-methods', 'TCE', 4),
  ('General Mathematics', 'tce-general-mathematics', 'TCE', 5),
  ('Mathematics Specialist', 'tce-mathematics-specialist', 'TCE', 6),
  ('Biology', 'tce-biology', 'TCE', 7),
  ('Chemistry', 'tce-chemistry', 'TCE', 8),
  ('Physics', 'tce-physics', 'TCE', 9),
  ('Psychology', 'tce-psychology', 'TCE', 10),
  ('Modern History', 'tce-modern-history', 'TCE', 11),
  ('Ancient History', 'tce-ancient-history', 'TCE', 12),
  ('Geography', 'tce-geography', 'TCE', 13),
  ('Legal Studies', 'tce-legal-studies', 'TCE', 14),
  ('Economics', 'tce-economics', 'TCE', 15),
  ('Accounting', 'tce-accounting', 'TCE', 16),
  ('Business Studies', 'tce-business-studies', 'TCE', 17),
  ('Health Studies', 'tce-health-studies', 'TCE', 18),
  ('Physical Sciences', 'tce-physical-sciences', 'TCE', 19),
  ('Sport Science', 'tce-sport-science', 'TCE', 20),
  ('Visual Art', 'tce-visual-art', 'TCE', 21),
  ('Art Production', 'tce-art-production', 'TCE', 22),
  ('Drama / Theatre Performance', 'tce-drama-theatre-performance', 'TCE', 23),
  ('Music', 'tce-music', 'TCE', 24),
  ('Media Production', 'tce-media-production', 'TCE', 25),
  ('Computer Science / Computational Thinking', 'tce-computer-science-computational-thinking', 'TCE', 26),
  ('Information Technology and Systems', 'tce-information-technology-and-systems', 'TCE', 27),
  ('Food and Nutrition', 'tce-food-and-nutrition', 'TCE', 28),
  ('Agricultural Systems', 'tce-agricultural-systems', 'TCE', 29),
  ('Philosophy / Religion and Philosophy', 'tce-philosophy-religion-and-philosophy', 'TCE', 30),
  ('English (T)', 'act-english-t', 'ACT', 1),
  ('English as an Additional Language (EAL/D)', 'act-english-as-an-additional-language-eal-d', 'ACT', 2),
  ('Essential English (A)', 'act-essential-english-a', 'ACT', 3),
  ('Mathematical Methods (T)', 'act-mathematical-methods-t', 'ACT', 4),
  ('Specialist Mathematics (T)', 'act-specialist-mathematics-t', 'ACT', 5),
  ('Mathematical Applications (T)', 'act-mathematical-applications-t', 'ACT', 6),
  ('Biology (T)', 'act-biology-t', 'ACT', 7),
  ('Chemistry (T)', 'act-chemistry-t', 'ACT', 8),
  ('Physics (T)', 'act-physics-t', 'ACT', 9),
  ('Psychology (T)', 'act-psychology-t', 'ACT', 10),
  ('Ancient History (T)', 'act-ancient-history-t', 'ACT', 11),
  ('Modern History (T)', 'act-modern-history-t', 'ACT', 12),
  ('Geography (T)', 'act-geography-t', 'ACT', 13),
  ('Legal Studies (T)', 'act-legal-studies-t', 'ACT', 14),
  ('Economics (T)', 'act-economics-t', 'ACT', 15),
  ('Accounting (T)', 'act-accounting-t', 'ACT', 16),
  ('Business (T)', 'act-business-t', 'ACT', 17),
  ('Politics (T)', 'act-politics-t', 'ACT', 18),
  ('Sociology (T)', 'act-sociology-t', 'ACT', 19),
  ('Exercise Science / Physical Education Studies (T)', 'act-exercise-science-physical-education-studies-t', 'ACT', 20),
  ('Health (T)', 'act-health-t', 'ACT', 21),
  ('Visual Arts (T)', 'act-visual-arts-t', 'ACT', 22),
  ('Media (T)', 'act-media-t', 'ACT', 23),
  ('Drama (T)', 'act-drama-t', 'ACT', 24),
  ('Music (T)', 'act-music-t', 'ACT', 25),
  ('Information Technology (T)', 'act-information-technology-t', 'ACT', 26),
  ('Digital Technologies / Computer Science (T)', 'act-digital-technologies-computer-science-t', 'ACT', 27),
  ('Hospitality / Food Science (A)', 'act-hospitality-food-science-a', 'ACT', 28),
  ('Religion and Society / Philosophy (T)', 'act-religion-and-society-philosophy-t', 'ACT', 29),
  ('Languages (T)', 'act-languages-t', 'ACT', 30),
  ('UCAT', 'ucat', 'TEST', 1),
  ('GAMSAT', 'gamsat', 'TEST', 2),
  ('LAT', 'lat', 'TEST', 3),
  ('SAT', 'sat', 'TEST', 4),
  ('ACT', 'act', 'TEST', 5),
  ('ISAT', 'isat', 'TEST', 6),
  ('STAT', 'stat', 'TEST', 7),
  ('uniTEST', 'unitest', 'TEST', 8),
  ('ESAT', 'esat', 'TEST', 9),
  ('NAPLAN', 'naplan', 'TEST', 10),
  ('AST', 'ast', 'TEST', 11),
  ('CASPer', 'casper', 'TEST', 12),
  ('Selective', 'selective', 'TEST', 13),
  ('OC', 'oc', 'TEST', 14);

alter table public.subjects alter column certificate_code set not null;

create index on public.subjects (certificate_code, position);
